name: publish
on: [push]
jobs:
  publish-hello-docker-image:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Login to GitHub Container Registry
        uses: docker/login-action@v1
        with:
          registry: ghcr.io
      - name: Build the hello-docker Docker image
        run: |
              docker build . --tag ghcr.io/Scy133/image-test:latest
              docker run ghcr.io/Scy133/image-test:latest
              docker push ghcr.io/Scy133/image-test:latest
